#
# circleci orb validate naturalcycles/doc-tools.yml
# circleci orb publish naturalcycles/doc-tools.yml naturalcycles/doc-tools@dev:4 #dev publish
# circleci orb publish increment naturalcycles/doc-tools.yml naturalcycles/doc-tools patch #new version
#
#
version: 2.1
description: Orb for release documentation creation and storage

executors:
  artifacts:
    docker:
      - image: naturalcycles/orb-artifacts:orb-1 # Image for 0.x.x orbs
    working_directory: ~/repo

jobs:

  #
  # Creates a release document (pdf) containing:
  # * Build info: version, build time
  # * Approvers (pulled from github PR reviewers) falls back to PR merger
  # * Released by (PR merger)
  # * Commit log
  # * PR body (converts markdown to html before making into pdf)
  #
  # Assumptions
  # * Assumes latest commit contains github standard text referencing merged PR ("/Merge pull request #(\d{1,6}) from/")
  #
  # Required env vars:
  # * GITHUB_TOKEN (with read access to PRs)
  # * RELEASE_DOC_TITLE (Title for h1)
  # * RELEASE_DOC_FILE (excl.pdf)
  # * VERSION - from previous jobs, assumed to reside in env state in workspace (/tmp/workspace/.env-state/.env)
  # * DEPLOYMENT_DATE - from previous jobs, assumed to reside in env state in workspace (/tmp/workspace/.env-state/.env)
  # * CIRCLE_PROJECT_REPONAME
  # * CIRCLE_PROJECT_USERNAME
  # * CIRCLE_SHA1
  #

  create-release-document:
    executor: artifacts
    steps:
      - attach-ws
      - load-state-env
      - run:
          name: Create release document
          command: |
            yarn --cwd /scripts/typescript/ tsn createReleaseDoc.ts
            mkdir -p /tmp/workspace/final-release-docs
            wkhtmltopdf /tmp/release.html /tmp/workspace/final-release-docs/${RELEASE_DOC_FILE}.pdf
      - persist-release-docs-ws

  #
  # Fetches artifacts from circleci github checks for the PR this commit represents.
  # Any amount of test reports is supported. Each should have a folder saved in job artifacts: junit-results/<test-xyz>
  # Each test must have:
  # * Any number of *.xml junit files
  # * A junit-variables.json containing at least: title, filename_prefix. (May contain any additional amount of headers, e.g. ..., "headers": {"name": "Version", "text": "1.0"})
  # Outputs PDFs in: workspace/final-release-docs/
  #
  # Assumptions
  # * Assumes latest commit contains github standard text referencing merged PR ("/Merge pull request #(\d{1,6}) from/")
  #
  # Required env vars:
  # * GITHUB_TOKEN (with read access to PRs)
  # * CIRCLE_CI_TOKEN (for current repo, used to fetch build artifacts)
  # * CIRCLE_PROJECT_REPONAME
  # * CIRCLE_PROJECT_USERNAME
  # * CIRCLE_SHA1
  #

  fetch-and-pdf-junit-reports:
    executor: artifacts
    steps:
      - attach-ws
      - load-state-env

      - run:
          name: "Fetch junit results from the github PR"
          command: yarn --cwd /scripts/typescript/ tsn fetchCircleCiJunitTestResults.ts
      - run:
          name: "Merge all xml files"
          command: globbing-command-wrapper.py --pattern "/tmp/workspace/junit-result/**/*.xml" --command "junit-merger.py merge LOCAL_PATTERN merged-report.xml"
      - run:
          name: Convert xml to html
          command: globbing-command-wrapper.py --pattern "/tmp/workspace/junit-result/**/merged-report.xml" --command "junit2html LOCAL_PATTERN merged-report.html"
      # Patch HTML report with data from junit-variables.json $VERSION env var in current context.
      # Update title, add version, add generic amount of headers and convert to PDF using filename from json
      - run:
          name: "Patch HTML report and generate pdf"
          command: globbing-command-wrapper.py --pattern "/tmp/workspace/junit-result/**/merged-report.html" --command "patch-and-pdf-html-report.py LOCAL_PATTERN"

      - run: yarn --cwd /scripts/typescript/ kpy --flat /tmp/workspace/junit-result/ **/*.pdf /tmp/workspace/final-release-docs/
      - persist-release-docs-ws

  #
  # Opinionated folder structure: Puts docs in: <specified folder>/${CIRCLE_PROJECT_REPONAME}/${VERSION}
  #
  # Requires environment variables:
  # RELEASE_DOCS_GDRIVE_FOLDER_ID - folder to which to upload files relative to.
  # RELEASE_DOCS_TEAMDRIVE_ID - optional team drive ID in which the above folder resides.
  # CIRCLE_PROJECT_REPONAME - auto-populated by circleci
  # GOOGLE_SERVICE_ACCOUNT - service account with write access to the specified folder.
  # VERSION - from previous jobs, assumed to reside in env state in workspace (workspace/.env-state/.env)
  #

  upload-release-docs-to-gdrive:
    executor: artifacts
    steps:
      - attach-ws
      - load-state-env
      - run:
          name: Upload release docs to gdrive
          command: |
            # Get google key from env var
            mkdir /home/circleci/.gdrive;
            echo $GOOGLE_SERVICE_ACCOUNT > /tmp/gcp-key.json

            # upload pdf files
            upload-to-teamdrive.py --service_account=/tmp/gcp-key.json\
                                   --teamdrive_id=${RELEASE_DOCS_TEAMDRIVE_ID}\
                                   --target_folder_id=${RELEASE_DOCS_GDRIVE_FOLDER_ID}\
                                   --files "/tmp/workspace/final-release-docs/*"\
                                   --flatten \
                                   --remote_folder_prefix ${CIRCLE_PROJECT_REPONAME}/${VERSION}\
                                   --overwrite
            rm -f /tmp/gcp-key.json

commands:
  attach-ws:
    steps:
      - attach_workspace:
          at: /tmp/workspace
  persist-release-docs-ws:
    steps:
      - persist_to_workspace:
          root: /tmp/workspace
          paths: ['final-release-docs'] # Don't blindly persist everything, since that might cause issues concurrency issues
  load-state-env:
    steps:
      - run:
          name: "Reading environment variable state into local context."
          command: cat /tmp/workspace/.env-state/.env >> $BASH_ENV ; source $BASH_ENV
  store-test-data:
    description: Opionated set of parameters to store from test for fetch-and-pdf-junit-reports job to use later. Does not persist the workspace.
    parameters:
      test-folder:
        type: string
      title:
        type: string
      filename_prefix:
        type: string
    steps:
      - run:
          when: always
          name: Storing test metadata to workspace
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "0" ]; then # Only store to workspace once to avoid parallelization issues.
              echo "{
                \"title\": \"<< parameters.title >>\",
                \"filename_prefix\": \"<< parameters.filename_prefix >>\",
                \"headers\": [
                {
                  \"name\": \"Branch\",
                  \"text\": \"${CIRCLE_BRANCH}\"
                },
                {
                  \"name\": \"CircleCI Job\",
                  \"text\": \"<a href=\\\"https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}\\\">${CIRCLE_BUILD_NUM}</a>\"
                }
                ]
              }" > /tmp/workspace/junit-result/<< parameters.test-folder >>/junit-variables.json
            fi
      - store_artifacts:
          when: always
          path: /tmp/workspace/junit-result
          destination: junit-result # Fetched from here by release documentation job
