#
# circleci orb validate naturalcycles/tools.yml && circleci orb publish increment naturalcycles/tools.yml naturalcycles/tools patch
#
version: 2.1
description: Tools orb

executors:
  node:
    docker:
      - image: naturalcycles/ci-node:latest
    working_directory: ~/repo

  node-gcloud:
    docker:
      - image: naturalcycles/ci-node-gcloud:latest
    working_directory: ~/repo

jobs:
  build-job:
    executor: node
    steps:
      - setup_node

      # build
      - run: yarn build

      # lint-all (withou --commitOnChanges)
      - run: yarn lint-all

      - job_end

  lint-job:
    executor: node
    steps:
      - setup_node

      # lint-all
      - run: yarn lint-all --commitOnChanges
      # todo: --commitOnChanges and --failOnChanges as boolean parameters

      - job_end

  release-job:
    description: Runs `yarn release`
    executor: node
    steps:
      - setup_node

      # release
      - release

      - job_end

  publish-job:
    executor: node
    steps:
      - setup_node

      # build
      - run: yarn build-prod

      # release
      - release

      - job_end

  test-job:
    parameters:
      CC_TEST_REPORTER_ID:
        type: string
        default: ""
    executor: node
    environment:
      CC_TEST_REPORTER_ID: << parameters.CC_TEST_REPORTER_ID >>
    steps:
      - setup_node

      # build
      - run: yarn build

      # test
      - test_ci

      - store_test_artifacts
      - job_end

  test-leaks-job:
    executor: node
    steps:
      - setup_node

      # test
      - run:
          name: test-leaks
          command: |
            yarn add -D patch-package weak-napi
            yarn patch-package
            # poor man's retry
            yarn test-leaks || yarn test-leaks

      - store_test_artifacts
      - job_end

  nightly-job:
    executor: node
    steps:
      - checkout

      # yarn (no cache)
      - run: yarn --no-lockfile

      - run: yarn build
      - run: yarn test-ci

      - store_test_artifacts
      - job_end

  deploy-gae-job:
    executor: node-gcloud
    steps:
      # not setup_node, because it runs in different Docker image! (so, yarn cache should NOT be saved there!)
      - checkout
      - install_yarn_deps

      - run:
          name: gcloud auth
          command: |
            gcloud version

            GCP_SERVICE_ACCOUNT_BY_BRANCH=`echo GCP_SERVICE_ACCOUNT_${CIRCLE_BRANCH} | tr a-z A-Z`

            if [ "${!GCP_SERVICE_ACCOUNT_BY_BRANCH}" ]; then
              echo ${!GCP_SERVICE_ACCOUNT_BY_BRANCH} | gcloud auth activate-service-account --key-file=-
            else
              echo $GCP_SERVICE_ACCOUNT | gcloud auth activate-service-account --key-file=-
            fi

      - run: yarn deploy-gae --logs
      - job_end

commands:
  setup_node:
    description: Performs usual initial steps for every node job
    steps:
      - checkout
      - install_yarn_deps

  install_yarn_deps:
    steps:
      - restore_cache_yarn
      - run:
          name: yarn --frozen-lockfile
          command: |
            # Will write $NPM_TOKEN to ~/.npmrc (if defined)
            [ ! -z "$NPM_TOKEN" ] && echo -e "always-auth=true\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            yarn --frozen-lockfile
      - save_cache_yarn

  restore_cache_yarn:
    steps:
      - restore_cache:
          key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}

  save_cache_yarn:
    steps:
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}

  release:
    steps:
      - run:
          name: Release (if needed)
          command: release

  test_ci:
    steps:
      - run:
          name: Test
          command: |
            # Use `cc-test-reporter` only if env variable is set
            [ ! -z "$CC_TEST_REPORTER_ID" ] && echo "Will use CC $CC_TEST_REPORTER_ID" || echo "Will NOT use CC $CC_TEST_REPORTER_ID"
            [ -z "$CC_TEST_REPORTER_ID" ] || cc-test-reporter before-build
            yarn test-ci
            [ -z "$CC_TEST_REPORTER_ID" ] || cc-test-reporter after-build -t lcov

  store_test_artifacts:
    steps:
      - store_test_results:
          path: tmp/jest
      - store_artifacts:
          path: tmp/jest
          destination: jest
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage-unit
      - store_artifacts:
          path: tmp/coverage-integration/lcov-report
          destination: coverage-integration

  job_end:
    description: Allows to run onJobSuccess.ts / onJobFail.ts hooks
    steps:
      - run:
          name: yarn tsn scripts/onJobSuccess.ts
          command: |
            if [ -f ./scripts/onJobSuccess.ts ]; then
                yarn tsn onJobSuccess.ts
            fi

      - run:
          name: yarn tsn scripts/onJobFail.ts
          when: on_fail
          command: |
            if [ -f ./scripts/onJobFail.ts ]; then
                yarn tsn onJobFail.ts
            fi
